/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/docs/App.vue')['default']
    ComponentsCssComponents: typeof import('./src/docs/components/CssComponents.vue')['default']
    ComponentsDocTables: typeof import('./src/docs/components/DocTables.vue')['default']
    ComponentsEventsTable: typeof import('./src/docs/components/EventsTable.vue')['default']
    ComponentsExamples: typeof import('./src/docs/components/Examples.vue')['default']
    ComponentsPropsTable: typeof import('./src/docs/components/PropsTable.vue')['default']
    ComponentsSlotsTable: typeof import('./src/docs/components/SlotsTable.vue')['default']
    Pages: typeof import('./src/docs/pages/index.vue')['default']
    PagesComponentsButtons: typeof import('./src/docs/pages/components/buttons.vue')['default']
    PagesComponentsContainers: typeof import('./src/docs/pages/components/containers.vue')['default']
    PagesComponentsDataVisualization: typeof import('./src/docs/pages/components/data-visualization.vue')['default']
    PagesComponentsDateAndTime: typeof import('./src/docs/pages/components/date-and-time.vue')['default']
    PagesComponentsFeedback: typeof import('./src/docs/pages/components/feedback.vue')['default']
    PagesComponentsInputs: typeof import('./src/docs/pages/components/inputs.vue')['default']
    PagesComponentsNavigation: typeof import('./src/docs/pages/components/navigation.vue')['default']
    PagesComponentsUtility: typeof import('./src/docs/pages/components/utility.vue')['default']
    PagesCssComponents: typeof import('./src/docs/pages/css/css-components.vue')['default']
    PagesPatternsFormGroup: typeof import('./src/docs/pages/patterns/form-group.vue')['default']
    PagesPatternsLayoutExternal: typeof import('./src/docs/pages/patterns/layout-external.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
