/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components/buttons': RouteRecordInfo<'/components/buttons', '/components/buttons', Record<never, never>, Record<never, never>>,
    '/components/containers': RouteRecordInfo<'/components/containers', '/components/containers', Record<never, never>, Record<never, never>>,
    '/components/data-visualization': RouteRecordInfo<'/components/data-visualization', '/components/data-visualization', Record<never, never>, Record<never, never>>,
    '/components/date-and-time': RouteRecordInfo<'/components/date-and-time', '/components/date-and-time', Record<never, never>, Record<never, never>>,
    '/components/feedback': RouteRecordInfo<'/components/feedback', '/components/feedback', Record<never, never>, Record<never, never>>,
    '/components/inputs': RouteRecordInfo<'/components/inputs', '/components/inputs', Record<never, never>, Record<never, never>>,
    '/components/navigation': RouteRecordInfo<'/components/navigation', '/components/navigation', Record<never, never>, Record<never, never>>,
    '/components/utility': RouteRecordInfo<'/components/utility', '/components/utility', Record<never, never>, Record<never, never>>,
    '/css/css-components': RouteRecordInfo<'/css/css-components', '/css/css-components', Record<never, never>, Record<never, never>>,
    '/patterns/form-group': RouteRecordInfo<'/patterns/form-group', '/patterns/form-group', Record<never, never>, Record<never, never>>,
  }
}
