/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/buttons': RouteRecordInfo<
      '/components/buttons',
      '/components/buttons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/containers': RouteRecordInfo<
      '/components/containers',
      '/components/containers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/data-visualization': RouteRecordInfo<
      '/components/data-visualization',
      '/components/data-visualization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/date-and-time': RouteRecordInfo<
      '/components/date-and-time',
      '/components/date-and-time',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/feedback': RouteRecordInfo<
      '/components/feedback',
      '/components/feedback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/inputs': RouteRecordInfo<
      '/components/inputs',
      '/components/inputs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/navigation': RouteRecordInfo<
      '/components/navigation',
      '/components/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/utility': RouteRecordInfo<
      '/components/utility',
      '/components/utility',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css/css-components': RouteRecordInfo<
      '/css/css-components',
      '/css/css-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css/table-prose': RouteRecordInfo<
      '/css/table-prose',
      '/css/table-prose',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/css/typography': RouteRecordInfo<
      '/css/typography',
      '/css/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patterns/data-table': RouteRecordInfo<
      '/patterns/data-table',
      '/patterns/data-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patterns/form-group': RouteRecordInfo<
      '/patterns/form-group',
      '/patterns/form-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/patterns/layout-external': RouteRecordInfo<
      '/patterns/layout-external',
      '/patterns/layout-external',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/docs/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/docs/pages/components/buttons.vue': {
      routes:
        | '/components/buttons'
      views:
        | never
    }
    'src/docs/pages/components/containers.vue': {
      routes:
        | '/components/containers'
      views:
        | never
    }
    'src/docs/pages/components/data-visualization.vue': {
      routes:
        | '/components/data-visualization'
      views:
        | never
    }
    'src/docs/pages/components/date-and-time.vue': {
      routes:
        | '/components/date-and-time'
      views:
        | never
    }
    'src/docs/pages/components/feedback.vue': {
      routes:
        | '/components/feedback'
      views:
        | never
    }
    'src/docs/pages/components/inputs.vue': {
      routes:
        | '/components/inputs'
      views:
        | never
    }
    'src/docs/pages/components/navigation.vue': {
      routes:
        | '/components/navigation'
      views:
        | never
    }
    'src/docs/pages/components/utility.vue': {
      routes:
        | '/components/utility'
      views:
        | never
    }
    'src/docs/pages/css/css-components.vue': {
      routes:
        | '/css/css-components'
      views:
        | never
    }
    'src/docs/pages/css/table-prose.vue': {
      routes:
        | '/css/table-prose'
      views:
        | never
    }
    'src/docs/pages/css/typography.vue': {
      routes:
        | '/css/typography'
      views:
        | never
    }
    'src/docs/pages/patterns/data-table.vue': {
      routes:
        | '/patterns/data-table'
      views:
        | never
    }
    'src/docs/pages/patterns/form-group.vue': {
      routes:
        | '/patterns/form-group'
      views:
        | never
    }
    'src/docs/pages/patterns/layout-external.vue': {
      routes:
        | '/patterns/layout-external'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
